name: Publish to Aliyun

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 下载代码
    - uses: actions/checkout@v2
    # 安装Nodejs
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn
    - run: yarn build
    # 部署到阿里云
    - name: Deploy to Aliyun
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        ARGS: "-avzr --delete"
        SOURCE: "build/"
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: "root"
        TARGET: ${{ secrets.TARGET }}